### GET MATCHES

GET http://localhost:3009/api/matches/


### CREATE MATCH

POST http://localhost:3009/api/matches
Content-Type: application/json

{
  "teamHome": "Germany",
  "teamAway": "Scotland",
  "startTime": "2024-06-14T19:00:00Z"
}

### DELETE Match

DELETE http://localhost:3009/api/matches/663120de4bb53e7ba8f8fb4d

###