GET http://localhost:3009/api/matchPredictions

###

POST http://localhost:3009/api/matchPredictions
Content-Type: application/json

{
  "goalsHome": 3,
  "goalsAway": 0,
  "user": "6633df7f1bb139263970426d",
  "match": "6633df7f1bb1392639704279"
}

###